/**
 * Generates no-icons/index.html from index.html.
 *
 * The variant is the same menu with the icons taken off the dropdown rows.
 * The Careers and Patient Intake Form marks in the utility tier stay, as do
 * the chevrons, the phone and the burger — only .pitem__icon goes.
 *
 * It is generated rather than hand-maintained so the two pages cannot drift:
 * edit index.html, then re-run this. Run it AFTER stamp-assets.js so the
 * variant inherits the same ?v= stamp.
 *
 *   node scripts/stamp-assets.js && node scripts/build-variant.js
 */
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const outDir = path.join(root, "no-icons");
let html = fs.readFileSync(path.join(root, "index.html"), "utf8");

/* 1. Drop the row icons, whole line and all. */
const iconLine = /^[ \t]*<svg class="pitem__icon"[\s\S]*?<\/svg>\r?\n/gm;
const removed = (html.match(iconLine) || []).length;
html = html.replace(iconLine, "");

/* 2. Most sprite symbols existed only for those rows. Keep the ones the
      page still points at and drop the rest, so the variant stays lean. */
const used = new Set([...html.matchAll(/<use href="#([\w-]+)"/g)].map((m) => m[1]));
const symbols = [...html.matchAll(/^[ \t]*<symbol id="([\w-]+)"[\s\S]*?<\/symbol>\r?\n/gm)];
let dropped = 0;
for (const [block, id] of symbols) {
  if (used.has(id)) continue;
  html = html.replace(block, "");
  dropped += 1;
}
/* A comment can be left stranded once its symbols go. */
html = html.replace(/^[ \t]*<!-- Menu additions: [^\n]*\n(?=\s*<\/defs>)/m, "");

/* 3. The variant sits one directory down. */
html = html.replace(/(href|src)="assets\//g, '$1="../assets/');

/* 4. Say which page this is. */
html = html
  .replace("<title>Navigation Menu —", "<title>Navigation Menu, no row icons —")
  .replace(
    'content="Two-tier navigation menu for Mason Dixon Animal Emergency Hospital, built on the site design system."',
    'content="Two-tier navigation menu for Mason Dixon Animal Emergency Hospital, with the dropdown rows set without icons."',
  )
  .replace(
    "<!doctype html>",
    "<!-- Generated by scripts/build-variant.js from ../index.html — do not edit by hand. -->\n<!doctype html>",
  );

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "index.html"), html);

console.log(`no-icons/index.html: removed ${removed} row icons, dropped ${dropped} unused sprite symbols`);
if (removed !== 29) {
  console.error(`expected 29 row icons, found ${removed}`);
  process.exit(1);
}
